module.exports.populate_torrent_string =
  ' -info_hash' +
  ' -last_scrape' +
  ' -torrent_announce' +
  ' -torrent_nfo' +
  ' -torrent_media_info' +
  ' -_other_torrents' +
  ' -_ratings' +
  ' -_replies' +
  ' -_subtitles' +
  ' -_thumbs' +
  ' -_all_files' +
  ' -resource_detail_info.adult' +
  ' -resource_detail_info.budget' +
  ' -resource_detail_info.genres' +
  ' -resource_detail_info.homepage' +
  ' -resource_detail_info.imdb_id' +
  ' -resource_detail_info.original_language' +
  ' -resource_detail_info.popularity' +
  ' -resource_detail_info.production_companies' +
  ' -resource_detail_info.production_countries' +
  ' -resource_detail_info.revenue' +
  ' -resource_detail_info.spoken_languages' +
  ' -resource_detail_info.status' +
  ' -resource_detail_info.tagline' +
  ' -resource_detail_info.credits' +
  ' -resource_detail_info.overview' +
  ' -resource_detail_info.images' +
  ' -resource_detail_info.alternative_titles' +
  ' -resource_detail_info.release_dates' +
  ' -resource_detail_info.belongs_to_collection' +

  ' -resource_detail_info.created_by' +
  ' -resource_detail_info.episode_run_time' +
  ' -resource_detail_info.first_air_date' +
  ' -resource_detail_info.last_air_date' +
  ' -resource_detail_info.in_production' +
  ' -resource_detail_info.languages' +
  ' -resource_detail_info.networks' +
  ' -resource_detail_info.number_of_episodes' +
  ' -resource_detail_info.number_of_seasons' +
  ' -resource_detail_info.origin_country' +
  ' -resource_detail_info.seasons' +
  ' -resource_detail_info.type';
